name: Build and Push Docker Image

on:
  push:
    branches:
      - custom
    paths-ignore:
      - 'docker/**'
      - '.github/**'
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - '.dockerignore'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set repository and image name to lowercase
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >>${GITHUB_ENV}
          echo "FULL_IMAGE_NAME=ghcr.io/${IMAGE_NAME,,}" >>${GITHUB_ENV}
        env:
          IMAGE_NAME: '${{ github.repository }}'

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.FULL_IMAGE_NAME }}:custom-${{ github.sha }}
            ${{ env.FULL_IMAGE_NAME }}:custom-latest
          build-args: |
            BUILD_HASH=${{ github.sha }}
